repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy.sh"
        language: system
        types: [python]
        require_serial: true
        verbose: true
